### PR TITLE
analyze the code on the CI

### PR DESCRIPTION
**Pull request by devoncarew**
- analyze the code on the CI

### CODE REVIEW

**Comment by devoncarew** [comment]
cc @lambdabaa

**Comment by lambdabaa** [comment]
There are also tons of errors coming out of `dartanalyzer` for me locally after landing the initial revision. Is there initial project configuration needed beyond `pub get`?

**Comment by devoncarew** [comment]
> Great, thanks! My only question is about `pub run test`. Does that assume that your entrypoint is `test/all.dart`? It does seem to run all of the tests correctly.

package:test uses the analyzer (I believe w/o resolution) to scan files in `test/` and determine which are tests. Having an `test/all.dart` which delegates to all other tests isn't necessary (but I don't believe can hurt).

**Comment by devoncarew** [comment]
> @devoncarew There are also tons of errors coming out of `dartanalyzer` for me locally after landing the initial revision. Is there initial project configuration needed beyond `pub get`? Do we need an analysis options file?

I see one failure in the CI on this PR:

https://travis-ci.org/dart-lang/tflite_native/builds/560757540#L507

Which I didn't address, as I think your in-progress PR will fix it.

We don't need an analysis options file locally unless we want to tighten things down to be more restrictive. I'd suggest we look into that after this lands, if desired.

> there are also tons of errors coming out of dartanalyzer for me locally

It shouldn't need any more config than `pub get`. What are the errors?

**Comment by devoncarew** [comment]
Also, I don't know how well dart:ffi will analyze...

**Comment by devoncarew** [comment]
And, I think you'll need to merge this PR.

**Comment by lambdabaa** [comment]
> It shouldn't need any more config than `pub get`. What are the errors?

Interestingly they aren't showing up on CI, so we can land. I'll also go ahead and add you as a collaborator. Thanks!

**Pull request merged**
