### PR TITLE
Remove use of deprecated FFI features via package:ffi.

### PR DESCRIPTION
**Pull request by sjindel-google**
/cc @dcharkes @mkustermann

### CODE REVIEW

**Comment by mkustermann** [comment]
We're getting close to the D26 release for which this is a prerequisite.

@lambdabaa Would you do us a favor and take a look?

**Comment by mkustermann** [comment]
LGTM

@lambdabaa The `Utf8` functionality we've added to `package:ffi`, the `Pointer.allocate` and `Pointer.free` are deprecated and will be removed very soon. We're a bit under time pressure for D26 so I hope it's ok with you for us to just merge it. If you have comments we can address them in a follow-up change.

**Comment by lambdabaa** [comment]
> @lambdabaa The `Utf8` functionality we've added to `package:ffi`, the `Pointer.allocate` and `Pointer.free` are deprecated and will be removed very soon. We're a bit under time pressure for D26 so I hope it's ok with you for us to just merge it. If you have comments we can address them in a follow-up change.

@mkustermann SGTM, though I just merged https://github.com/dart-lang/tflite_native/commit/439f580a2de69b576f13d11e4f681789f4163553 which looks like it also needs to be updated? /cc @sjindel-google @mkustermann

**Comment by dcharkes** [comment]
@lambdabaa I left some comments on the commit. If you build dart locally after https://dart-review.googlesource.com/c/sdk/+/121708 lands, you'll have the latest API (as we will ship with D26). We can also take a look for you tomorrow if you prefer.

**Pull request merged**
